AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image Generator Lambda Function

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        BUCKET_NAME: pgr301-couch-explorers
        CANDIDATE_NUMBER: 63

Resources:
  ImageGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: oppgave/
      Handler: app.lambda_handler
      Runtime: python3.11
      Events:
        GenerateImage:
          Type: Api
          Properties:
            Path: /generate-image
            Method: post
      Policies:
        - S3WritePolicy:
            BucketName: pgr301-couch-explorers
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: "*"
Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate-image"