name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Login Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build docker image
      - name: Build Docker Image
        run: |
          cd Oppgave3
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/imagegenerator:latest .

      # tag docker image with sha
      - name: Tag Docker Image
        run: |
          cd Oppgave3
          COMMIT_SHA=${GITHUB_SHA::7}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/imagegenerator:latest ${{ secrets.DOCKERHUB_USERNAME }}/imagegenerator:$COMMIT_SHA

      # Push docker image to docker hub
      - name: Push Docker Image
        run: |
          cd Oppgave3
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/imagegenerator:latest
          COMMIT_SHA=${GITHUB_SHA::7}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/imagegenerator:$COMMIT_SHA

      # Docker test
      - name: Run Docker Container
        run: |
          docker run -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
                 -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
                 -e SQS_QUEUE_URL=${{ secrets.SQS_QUEUE_URL }} \
                 ${{ secrets.DOCKERHUB_USERNAME }}/imagegenerator:latest "me on top of a pyramid"
